#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use yii\console\Application;

require(__DIR__ . '/vendor/autoload.php');

defined('YII_ENV') or define('YII_ENV', 'dev');
defined('YII_ENV_PROD') or define('YII_ENV_PROD', YII_ENV === 'production');
defined('YII_DEBUG') or define('YII_DEBUG', YII_ENV === 'dev');

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

require(__DIR__ . '/sample/config/bootstrap.php');

$config = require(__DIR__ . '/sample/config/console.php');

$application = new Application($config);
$exitCode = $application->run();
exit($exitCode);
