<?php

// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace rhertogh\Yii2Oauth2Server\models\base;

use Yii;

/**
 * This is the base-model class for table "oauth2_access_token".
 *
 * @property string $id
 * @property string $identifier
 * @property integer $client_id
 * @property integer $user_id
 * @property integer $type
 * @property string $mac_key
 * @property integer $mac_algorithm
 * @property integer $allowance
 * @property integer $allowance_updated_at
 * @property string $expiry_date_time
 * @property integer $enabled
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \rhertogh\Yii2Oauth2Server\models\Oauth2AccessTokenScope[] $accessTokenScopes
 * @property \rhertogh\Yii2Oauth2Server\models\Oauth2Client $client
 * @property \rhertogh\Yii2Oauth2Server\models\Oauth2RefreshToken[] $refreshTokens
 * @property \rhertogh\Yii2Oauth2Server\models\Oauth2Scope[] $scopes
 * @property string $aliasModel
 *
 * phpcs:disable Generic.Files.LineLength.TooLong
 */
abstract class Oauth2AccessToken extends \rhertogh\Yii2Oauth2Server\models\base\Oauth2BaseActiveRecord
{


    /**
     * @inheritdoc
     */
    //public static $tableName = 'oauth2_access_token';



    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['identifier', 'client_id', 'type', 'expiry_date_time', 'created_at', 'updated_at'], 'required'],
            [['client_id', 'user_id', 'type', 'mac_algorithm', 'allowance', 'allowance_updated_at', 'enabled', 'created_at', 'updated_at'], 'integer'],
            [['expiry_date_time'], 'safe'],
            [['identifier'], 'string', 'max' => 255],
            [['mac_key'], 'string', 'max' => 500],
            [['identifier'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('oauth2', 'ID'),
            'identifier' => Yii::t('oauth2', 'Identifier'),
            'client_id' => Yii::t('oauth2', 'Client ID'),
            'user_id' => Yii::t('oauth2', 'User ID'),
            'type' => Yii::t('oauth2', 'Type'),
            'mac_key' => Yii::t('oauth2', 'Mac Key'),
            'mac_algorithm' => Yii::t('oauth2', 'Mac Algorithm'),
            'allowance' => Yii::t('oauth2', 'Allowance'),
            'allowance_updated_at' => Yii::t('oauth2', 'Allowance Updated At'),
            'expiry_date_time' => Yii::t('oauth2', 'Expiry Date Time'),
            'enabled' => Yii::t('oauth2', 'Enabled'),
            'created_at' => Yii::t('oauth2', 'Created At'),
            'updated_at' => Yii::t('oauth2', 'Updated At'),
        ];
    }

    /**
     * @return \rhertogh\Yii2Oauth2Server\interfaces\models\queries\Oauth2AccessTokenScopeQueryInterface|\yii\db\ActiveQuery
     */
    public function getAccessTokenScopes()
    {
        return $this->hasMany(\rhertogh\Yii2Oauth2Server\models\Oauth2AccessTokenScope::className(), ['access_token_id' => 'id'])->inverseOf('accessToken');
    }

    /**
     * @return \rhertogh\Yii2Oauth2Server\interfaces\models\queries\Oauth2ClientQueryInterface|\yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(\rhertogh\Yii2Oauth2Server\models\Oauth2Client::className(), ['id' => 'client_id'])->inverseOf('accessTokens');
    }

    /**
     * @return \rhertogh\Yii2Oauth2Server\interfaces\models\queries\Oauth2RefreshTokenQueryInterface|\yii\db\ActiveQuery
     */
    public function getRefreshTokens()
    {
        return $this->hasMany(\rhertogh\Yii2Oauth2Server\models\Oauth2RefreshToken::className(), ['access_token_id' => 'id'])->inverseOf('accessToken');
    }

    /**
     * @return \rhertogh\Yii2Oauth2Server\interfaces\models\queries\Oauth2ScopeQueryInterface|\yii\db\ActiveQuery
     */
    public function getScopes()
    {
        return $this->hasMany(\rhertogh\Yii2Oauth2Server\models\Oauth2Scope::className(), ['id' => 'scope_id'])->via('accessTokenScopes');
    }



    /**
     * @inheritdoc
     * @return \rhertogh\Yii2Oauth2Server\interfaces\models\queries\Oauth2AccessTokenQueryInterface|\yii\db\ActiveQuery the active query used by this AR class.
     */
    public static function find()
    {
        return Yii::createObject(\rhertogh\Yii2Oauth2Server\interfaces\models\queries\Oauth2AccessTokenQueryInterface::class, [get_called_class()]);
    }
}
